export const PROJECTS = [
  {
    id: "enterprise",
    index: "01",
    title: "B端设计",
    subtitle: "客户信息系统",
    cover: "/cis-project.webp",
    summary: "客户信息系统完整页面展示。",
    isFullPageImage: true,
  },
  {
    id: "mobile-ai",
    index: "02",
    title: "移动端",
    subtitle: "AI舆情助手",
    cover: "/ai-sentiment.webp",
    summary: "",
    isFullPageImage: true,
  },
  {
    id: "dataviz-brain",
    index: "03",
    title: "能源数字大脑",
    subtitle: "",
    cover: "/energy-brain.webp",
    summary: "",
    isFullPageImage: true,
    hotspotVideo: {
      src: "https://wfl91ymaecqivvtz.public.blob.vercel-storage.com/%E5%90%88%E6%88%90%201.mp4",
      baseWidth: 1920,
      baseHeight: 16384,
      x: 730,
      y: 9310,
      width: 980,
      height: 1500,
    },
  },
  {
    id: "smart-gate",
    index: "03",
    title: "智慧门站",
    subtitle: "",
    cover: "/smart-gate.webp",
    summary: "",
    isFullPageImage: true,
    hotspotVideo: {
      src: "https://wfl91ymaecqivvtz.public.blob.vercel-storage.com/%E6%99%BA%E6%85%A7%E5%9C%BA%E7%AB%99.mp4",
      baseWidth: 3590,
      baseHeight: 16000,
      x: 0,
      y: 14800,
      width: 3590,
      height: 1200,
    },
  },
  {
    id: "iot-hall",
    index: "03",
    title: "IOT展厅",
    subtitle: "",
    cover: "/assets/overview-03.webp",
    video: "https://wfl91ymaecqivvtz.public.blob.vercel-storage.com/iot%E8%A7%86%E9%A2%91.mp4",
    summary:
      "公司展厅项目 独立完成从创意构思到3D建模到AE动效的全流程制作。以叙事化镜头语言串联\"终端-传输-算力-云端\"全链路，将物联网抽象业务架构转化为可感知的视觉叙事",
  },
  {
    id: "ops-visual",
    index: "04",
    title: "运营视觉类",
    subtitle: "",
    cover: "/ops-visual.webp",
    summary: "",
    isFullPageImage: true,
    hideBack: false,
  },
  {
    id: "digital-human",
    index: "04",
    title: "数字人",
    subtitle: "",
    cover: "/digital-human.webp",
    summary: "",
    isFullPageImage: true,
    hideBack: false,
    overlayVideo: {
      src: "https://wfl91ymaecqivvtz.public.blob.vercel-storage.com/%E5%AD%97%E5%B9%95%E7%89%88%E6%9C%AC.mp4",
      baseWidth: 1920,
      baseHeight: 5849,
      x: 260,
      y: 4414,
      width: 1390,
      height: 784,
    },
  },
];
